---

- name: Ensure redis is installed.
  yum:
    name: "{{ redis_package_name }}"
    state: present

- name: Ensure redis is started and enabled to start at boot.
  service: name="{{ redis_package_name }}" state=started enabled=yes

- name: Add redis configuration file.
  template:
    src: "{{ redis_template }}"
    dest: "/etc/{{ redis_config_name }}"
    force: yes
    owner: redis
    group: root
    mode: 0644
  notify: restart redis