---
- name: Add repository 'epel-release'
  yum: name=epel-release state=installed

- name: Add repository 'remi-repo'
  command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

- name: install php70
  yum: name={{ item }} enablerepo=epel,remi,remi-php70 state=installed
  with_items:
    - php70
    - php70-php-mcrypt
    - php70-php-mbstring
    - php70-php-fpm
    - php70-php-gd
    - php70-php-xml
    - php70-php-pdo
    - php70-php-zip
    - php70-php-intl
    - php70-php-soap
    - php70-php-pdo_mysql  

- name : link env file
  command: ln -s /opt/remi/php70/enable /etc/profile.d/php70.sh creates=/etc/profile.d/php70.sh
  notify: restart php-fpm

- name: Set ownership for php sessions
  file:
    path: "{{ php_fpm_lib_path }}"
    owner: root
    group: "{{ __nginx_user }}"
    recurse: yes


- name: Add php.ini configuration file.
  template:
    src: "php.ini.j2"
    dest: "{{ php_fpm_path }}/php.ini"
    force: yes
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm

- name: Add php-fpm pool configuration file.
  template:
    src: "{{ php_fpm_template }}"
    dest: "{{ php_fpm_pool_path }}/{{ php_fpm_pool_name.split(' ')[0] ~ '.conf' }}"
    force: yes
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm