---
- name: Set repo.magento.com composer keys
  shell: composer config --global http-basic.repo.magento.com {{ magento_account_public_key }} {{ magento_account_private_key }}

- name: Ensure magento project directory exists
  file: path="{{ magento_root_dir }}" state=directory

- name: Create magento project
  shell: composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition . 2.0.1
  args:
    chdir: "{{ magento_root_dir }}"
    creates: "{{ magento_root_dir }}/composer.json"
  notify: reload nginx

- name: Set file/directory ownership to nginx user
  file:
    path: "{{ magento_root_dir }}"
    owner: "{{ __nginx_user }}"
    group: "{{ __nginx_user }}"
    recurse: yes

- name: Recursively change ownership of a directory
  file:
    path: "{{ magento_root_dir }}"
    state: directory
    recurse: yes
    owner: "{{ __nginx_user }}"
    group: "{{ __nginx_user }}"
    mode: u+rw-x+X,g+rw-x+X,o-rwx

- name: set $MAGE_MODE developer
  lineinfile:
    path: "{{ magento_root_dir }}/nginx.conf.sample"
    regexp: 'set $MAGE_MODE default'
    line: set $MAGE_MODE developer

- name: set $MAGE_MODE developer
  lineinfile:
    path: /var/www/html/magento/nginx.conf.sample
    regexp: 'default;'
    line: set $MAGE_MODE developer;
~                                     
